services:
  pg-server:
    image: postgres
    container_name: pg-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: